#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"
DRY_RUN=false
YES=false
DEV=false
REGENERATE=false
APP_VERSION="v1.0.0"

for arg in "$@"; do
    case "$arg" in
        --dry-run) DRY_RUN=true ;;
        --yes|-y) YES=true ;;
        --dev) DEV=true ;;
        --regenerate) REGENERATE=true ;;
        --version=*) APP_VERSION="${arg#*=}" ;;
        *) echo "Unknown argument: $arg" >&2; exit 2 ;;
    esac
done

say() { printf '\n==> %s\n' "$*"; }
ok() { printf '  OK: %s\n' "$*"; }
run() { if $DRY_RUN; then printf '  [dry-run] %q ' "$@"; printf '\n'; else "$@"; fi; }
rand_hex() { openssl rand -hex "${1:-16}"; }

command -v docker >/dev/null || { echo "docker is required" >&2; exit 1; }
command -v openssl >/dev/null || { echo "openssl is required" >&2; exit 1; }
command -v python3 >/dev/null || { echo "python3 is required" >&2; exit 1; }
docker compose version >/dev/null || { echo "Docker Compose v2 is required" >&2; exit 1; }

declare -a COMPOSE=(docker compose -f compose.yaml)
$DEV && COMPOSE+=(-f compose.dev.yaml)
# Auto-include GPU overlay if NVIDIA GPU is available
if [ -f compose.gpu.yaml ] && command -v nvidia-container-cli >/dev/null 2>&1; then
    COMPOSE+=(-f compose.gpu.yaml)
fi

say "Configuration"
if [ -f .env ] && ! $REGENERATE; then
    ok "Preserving existing .env (use --regenerate to replace it)"
elif $DRY_RUN; then
    echo "  [dry-run] would generate .env with mode 0600"
else
    if [ -f .env ] && ! $YES; then
        read -r -p "Replace existing .env? [y/N] " answer
        case "$answer" in [Yy]*) ;; *) echo "Aborted"; exit 0 ;; esac
    fi
    POSTGRES_PASSWORD="$(rand_hex 24)"
    S3_SECRET_KEY="$(rand_hex 32)"
    umask 077
    cat > .env <<EOF
# Generated by setup.sh
APP_VERSION=${APP_VERSION}
APP_BIND_ADDRESS=127.0.0.1
APP_PORT=8000
POSTGRES_DB=library
POSTGRES_USER=library
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgresql://library:${POSTGRES_PASSWORD}@postgres:5432/library
REDIS_URL=redis://redis:6379/0
OLLAMA_URL=http://ollama:11434
EMBED_MODEL=bge-large
EMBED_DIMENSION=1024
QDRANT_URL=http://qdrant:6333
QDRANT_COLLECTION=library_documents
IMAGE_COLLECTION=library_images
IMAGE_SEARCH_MIN_SCORE=0.2
S3_ENDPOINT=seaweedfs:8333
S3_ACCESS_KEY=library_admin
S3_SECRET_KEY=${S3_SECRET_KEY}
S3_BUCKET=library-files
SEAWEEDFS_S3_CONFIG_PATH=./.state/seaweedfs-s3.json
EMBED_BATCH_SIZE=512
EMBED_BATCH_DELAY=0.0
OLLAMA_MAX_LOADED_MODELS=1
OLLAMA_NUM_PARALLEL=2
WORKER_CONCURRENCY=2
CORS_ORIGINS=http://localhost:8000
EOF
    chmod 600 .env
    ok "Generated .env"
fi

env_value() {
    local key="$1" default="${2:-}" value
    if [ ! -f .env ]; then printf '%s' "$default"; return; fi
    value="$(awk -F= -v key="$key" '$1 == key {sub(/^[^=]*=/, ""); print; exit}' .env)"
    printf '%s' "${value:-$default}"
}

say "Private object-store identity"
if $DRY_RUN; then
    echo "  [dry-run] would generate .state/seaweedfs-s3.json with mode 0600"
else
    mkdir -p .state
    S3_ACCESS_KEY_VALUE="$(env_value S3_ACCESS_KEY library_admin)" \
    S3_SECRET_KEY_VALUE="$(env_value S3_SECRET_KEY)" \
        python3 -c 'import json, os, pathlib
p = pathlib.Path(".state/seaweedfs-s3.json")
payload = {"identities": [{"name": "library", "credentials": [{"accessKey": os.environ["S3_ACCESS_KEY_VALUE"], "secretKey": os.environ["S3_SECRET_KEY_VALUE"]}], "actions": ["Admin", "Read", "Write", "List", "Tagging"]}]}
p.write_text(json.dumps(payload, separators=(",", ":")) + "\n")'
    chmod 600 .state/seaweedfs-s3.json
    ok "Generated private SeaweedFS S3 identity"
fi

say "Compose validation"
if $DRY_RUN && [ ! -f .env ]; then
    ok "Skipped resolved validation until .env exists"
else
    "${COMPOSE[@]}" config --quiet
    ok "Resolved Compose model is valid"
fi

say "Starting stateful dependencies"
run "${COMPOSE[@]}" up -d --wait postgres redis qdrant seaweedfs ollama

say "Embedding model"
run "${COMPOSE[@]}" exec -T ollama ollama pull "$(env_value EMBED_MODEL bge-large)"

say "Private object-store bucket"
run "${COMPOSE[@]}" run --rm -T app python -c \
    "from api.services.object_store import get_object_store; get_object_store().ensure_bucket()"

say "Database migrations"
run "${COMPOSE[@]}" run --rm -T app alembic upgrade head

say "Starting application services"
run "${COMPOSE[@]}" up -d --wait app worker beat

if ! $DRY_RUN; then
    curl -fsS "http://127.0.0.1:$(env_value APP_PORT 8000)/api/health" >/dev/null
    ok "API is healthy"
fi

printf '\nSelf-Hosted Library is ready at http://localhost:%s\n' "$(env_value APP_PORT 8000)"
printf 'Run ./doctor.sh for a full deployment check.\n'
